spring.application.name=mobileshop

server.port=8777

spring.datasource.url=jdbc:postgresql://localhost:5432/mobileshop1
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=yUAM4LkjSHOP587HAFTYuyGSHJIP9ttI
jwt.expiration=86400000

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kuldipparbat99@gmail.com
spring.mail.password=tinovvocwftpzxcu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App URL (for reset links)
app.frontend.url=http://localhost:4200
app.admin.email=admin@mobileshop.com
app.admin.password=Admin@123456

spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.mobileshop.tenant.TenantIdentifierResolver
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.mobileshop.tenant.SchemaMultiTenantConnectionProvider