spring.application.name=mobileshop

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=${SECRET_KEY}
jwt.expiration=86400000

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App URL (for reset links)
app.frontend.url=https://mobileshop-ui.vercel.app
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

spring.jpa.properties.hibernate.multiTenancy=SCHEMA
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.mobileshop.tenant.TenantIdentifierResolver
spring.jpa.properties.hibernate.multi_tenant_connection_provider=com.mobileshop.tenant.SchemaMultiTenantConnectionProvider
